_far shelf/course CS50 Web/1 django/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("entry/<str:title>", views.entry, name="entry"),
    path("results/<str:keyword>", views.results, name="results"),
    path("write/", views.write, name="write"),
    path("write/<str:entry>", views.write, name="write"),
]

_far shelf/course CS50 Web/1 django/first_django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("newyear/", include('newyear.urls')),
    path("tasks/", include('tasks.urls')),
    path("polls/", include('polls.urls')),
    path("wiki/", include('encyclopedia.urls')),
    path("admin/", admin.site.urls),
    path("", include('hello.urls')),
]

_far shelf/course CS50 Web/1 django/hello/urls.py
from django.urls import path
from . import views

app_name = "hello"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.name, name="name"),
]

_far shelf/course CS50 Web/1 django/newyear/urls.py
from django.urls import path
from . import views

app_name = "newyear"
urlpatterns = [
    path("", views.index, name="index"),
]

_far shelf/course CS50 Web/1 django/polls/urls.py
from django.urls import path
from . import views


app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

_far shelf/course CS50 Web/1 django/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

_far shelf/course CS50 Web/1 django/encyclopedia/models.py
from django.db import models

# Create your models here.

_far shelf/course CS50 Web/1 django/encyclopedia/views.py
import markdown2
import random

from django import forms
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404

from . import util


class SearchForm(forms.Form):
    search_key = forms.CharField(
        empty_value=None, label="", 
        widget=forms.TextInput(attrs={'placeholder': "search encyclopedia"})
    )


class EditorForm(forms.Form):
    title = forms.CharField(empty_value=None, label="Page name:")
    textarea = forms.CharField(
        empty_value=None, label="Write your article:",
        widget=forms.Textarea
    )


def index(request):
    if request.method == 'GET':
        entries = [entry.capitalize() for entry in util.list_entries()]
        return render(request, "wiki/index.html", {'form': SearchForm(), 'entries': entries})
    
    elif request.method == 'POST':
        keyword = "None"
        entries = util.list_entries()
        form = SearchForm(request.POST)        
        if form.is_valid():
            search_key = form.cleaned_data['search_key'].strip().lower()
            if search_key in entries:
                return HttpResponseRedirect(reverse("wiki:entry", args=(search_key,)))
            else:
                keyword = search_key
        
        return HttpResponseRedirect(reverse("wiki:results", args=(keyword,)))


def entry(request, title):
    title = str(title).strip().lower()
    if title == "random":
        title = random.choice(util.list_entries())
    html_text = markdown2.markdown(
        util.get_entry(title)
    )
    return render(
        request, "wiki/entry.html", 
        {'title': title, 'form': SearchForm(), 'html_text': html_text}
    )


def results(request, keyword):
    entries = []
    if keyword != "None":
        entries = [
            entry.capitalize() for entry in util.list_entries() if keyword in entry
        ]
    return render(request, "wiki/results.html", {'form': SearchForm(), 'entries': entries})


def write(request, entry=None):
    if request.method == 'GET':
        if not entry or entry == "new":
            context = {'form': SearchForm(), 'page_name': "New Page", 
                       'editor_form': EditorForm()}
        else:
            entry = entry.strip().lower()
            if entry not in util.list_entries():
                raise Http404("Article does not exist.")

            text = util.get_entry(entry)
            context = {
                'form': SearchForm(), 'page_name': entry, 
                'editor_form': EditorForm(initial={'title': entry, 'textarea': text})
            }

        return render(request, "wiki/write.html", context)

    elif request.method == 'POST':
        form = EditorForm(request.POST)        
        if not form.is_valid():
            s = "Error: the form is filled out incorrectly."
        else:
            title = form.cleaned_data['title'].strip().lower()
            textarea = form.cleaned_data['textarea']
            util.save_entry(title, textarea)
            s = "Article updated." if title in util.list_entries() else "Article saved."           
            
        context = {'form': SearchForm(), 'editor_form': form, 'page_name': "New Page", 'message': s}
        return render(request, "wiki/write.html", context)    

_far shelf/course CS50 Web/1 django/encyclopedia/templates/wiki/entry.html
{% extends "wiki/layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    {{ html_text|safe }}
{% endblock %}

_far shelf/course CS50 Web/1 django/encyclopedia/templates/wiki/index.html
{% extends "wiki/layout.html" %}

{% block title %}Wiki{% endblock %}

{% block body %}
  <header>
    <h1>All Pages</h1>
  </header>

  <section class='main'>
    {% if entries %}
      <ul>
        {% for entry in entries %}
          <li>
            <a href="{% url 'wiki:entry' entry %}">{{ entry }}</a>

            <sub class='edit'><a href="{% url 'wiki:write' entry %}">(edit)</a></sub>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No entries to read.</p>
    {% endif %}
  </section>
{% endblock %}

_far shelf/course CS50 Web/1 django/encyclopedia/templates/wiki/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content='width=divice-width, height=device-height, initial-scale=1.0'>
    <link rel='shortcut icon' type='image/ico' href="{% static 'base/favicon.ico' %}">
    <link rel='stylesheet' href="{% static 'wiki/styles.css' %}">
  </head>

  <body>

    <nav>
      <section class='nav' id='title'>
        <h1>Wiki</h1>
      </section>

      <form action='{% url "wiki:index" %}' method='POST' class='nav'>
        {% csrf_token %}
        {{ form }}

        <a href="{% url 'wiki:index' %}" class='global-nav' id='home'>
          <div>HOME</div>
        </a>
        <button type='submit' class='global-nav' id='search'>Search</button>
      </form>   

      <section class='nav' id='global-nav'>
        <a href="{% url 'hello:index' %}" class='global-nav'>
          <div>hello</div>
        </a>
        <a href="{% url 'newyear:index' %}" class='global-nav'>
          <div>newyear</div>
        </a>
        <a href="{% url 'tasks:index' %}" class='global-nav'>
          <div>tasks</div>
        </a>
        <a href="{% url 'polls:index' %}" class='global-nav'>
          <div>polls</div>
        </a>
      </section class='nav'>

      <section class='nav'>
        <a href="{% url 'wiki:write' 'new' %}">
          <button class='options'>Create New Page</button>
        </a>
      </section>

      <section class='nav'>
        <a href="{% url 'wiki:entry' 'random' %}">
          <button class='options'>Random Page</button>
        </a>
      </section>
    </nav>

    <main>
      {% block body %}
      {% endblock %}
    </main>

  </body>

</html>

_far shelf/course CS50 Web/1 django/encyclopedia/templates/wiki/results.html
{% extends "wiki/layout.html" %}

{% block title %}Results{% endblock %}

{% block body %}
  <header>
    <h1>Search results:</h1>
  </header>

  <section class='main'>
    {% if entries %}
      <ul>
        {% for entry in entries %}
          <li>
            <a href="{% url 'wiki:entry' entry %}">{{ entry }}</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No matches.</p>
    {% endif %}
  </section>
{% endblock %}

_far shelf/course CS50 Web/1 django/encyclopedia/templates/wiki/write.html
{% extends "wiki/layout.html" %}

{% block title %}{{ page_name }}{% endblock %}

{% block body %}
  <section class='editor'>
    <form action='{% url "wiki:write" %}' method='POST'>
      {% csrf_token %}
      {{ editor_form }}
      <button type='submit' id='save'>Save</button>
    </form>
    <p>{{ message }}</p>
  </section>
{% endblock %}